import { FormEvent, useEffect, useState } from 'react'
import { Link, Route, Routes } from 'react-router-dom'
import { ArrowRight, Battery, CheckCircle2, Cpu, Leaf, LocateFixed, LogOut, Recycle, ShieldCheck, Sparkles, Upload, UserRound, X, XCircle } from 'lucide-react'
import { api, clearToken, getToken, saveToken } from './services/api'
import type { Analysis, Recycler, User } from './types'

const RecyclerList = ({ recyclers }: { recyclers: Recycler[] }) => <div className="recycler-list">{recyclers.length ? recyclers.map(item => <article className="recycler-card" key={item.id}><div><span className={item.verified ? 'badge verified' : 'badge'}>{item.verified ? 'Verified' : 'Demo listing'}</span><h3>{item.name}</h3><p>{item.city}, {item.state} · {item.distance_km?.toFixed(1) ?? '—'} km away</p><p>{item.accepted_waste_types.join(' · ')}</p></div><div className="score"><strong>{item.score?.toFixed(0) ?? '—'}</strong><small>match score</small></div></article>) : <div className="empty">No recycler matches yet. Try another location or a broader radius.</div>}</div>

function AuthModal({ close, signedIn }: { close: () => void; signedIn: (user: User) => void }) { const [mode,setMode]=useState<'login'|'register'>('login'); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget);try{const result=mode==='login'?await api.login(String(data.get('email')),String(data.get('password'))):await api.register(String(data.get('name')),String(data.get('email')),String(data.get('password')));saveToken(result.token);signedIn(result.user);close()}catch(cause){setError(cause instanceof Error?cause.message:'Could not complete your request.')}finally{setBusy(false)}};return <div className="modal-backdrop" role="dialog" aria-modal="true"><section className="auth-modal"><button className="icon-button close" onClick={close} aria-label="Close"><X size={20}/></button><div className="auth-mark"><Recycle size={22}/></div><p className="eyebrow">YOUR RESPONSIBLE TECH JOURNEY</p><h2>{mode==='login'?'Welcome back':'Create your account'}</h2><p className="subtle">{mode==='login'?'Sign in to keep your e-waste journey organised.':'Save your place in a more circular digital future.'}</p><form onSubmit={submit}>{mode==='register'&&<label>Full name<input name="name" required minLength={2} placeholder="Your name"/></label>}<label>Email address<input name="email" required type="email" placeholder="you@example.com"/></label><label>Password<input name="password" required minLength={8} type="password" placeholder="At least 8 characters"/></label>{error&&<p className="form-error">{error}</p>}<button className="button primary wide" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'} <ArrowRight size={17}/></button></form><button className="text-button" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'New here? Create an account':'Already have an account? Sign in'}</button></section></div>}

function Header({user,signOut}:{user?:User;signOut:()=>void}){const[auth,setAuth]=useState(false);return <><header><Link className="brand" to="/"><span className="brand-mark"><Recycle size={20}/></span>Eco<span>Cycle</span></Link><nav><Link to="/analyze">Assess device</Link><Link to="/recyclers">Find recyclers</Link></nav>{user?<div className="account"><span><UserRound size={16}/>{user.full_name.split(' ')[0]}</span><button className="icon-button" onClick={signOut} title="Sign out"><LogOut size={17}/></button></div>:<button className="button signin" onClick={()=>setAuth(true)}><UserRound size={16}/> Sign in</button>}</header>{auth&&<AuthModal close={()=>setAuth(false)} signedIn={()=>window.location.reload()}/>}</>}

function Home(){const[part,setPart]=useState('Screen · reusable materials');const parts=[['part-screen','Screen','Reusable glass'],['part-chip','Circuit','Recoverable metals'],['part-battery','Battery','Handle separately']];return <><section className="hero"><div className="hero-copy"><p className="eyebrow"><Sparkles size={14}/> SMARTER E-WASTE DECISIONS</p><h1>Give every device a <em>better next life.</em></h1><p>Discover a responsible path for old technology—from safe preparation to a recycler near you.</p><div className="actions"><Link className="button primary" to="/analyze">Assess a device <ArrowRight size={18}/></Link><Link className="button" to="/recyclers">Find a recycler</Link></div><div className="trust-row"><span><ShieldCheck/> Safety-first guidance</span><span><Leaf/> Circular by design</span></div></div><div className="hero-panel"><div className="ambient-grid"/><div className="device-visual" aria-label="Exploded view of an electronic device"><div className="laptop-lid"><div className="screen-glow"/></div><div className="laptop-base"><div className="keyboard"/></div><div className="chip"><Cpu size={20}/></div><div className="battery"><Battery size={19}/></div></div><div className="part-labels">{parts.map(([id,label,detail])=><button className={`part ${id}`} onClick={()=>setPart(`${label} · ${detail}`)} key={id}><i/>{label}</button>)}</div><div className="material-readout"><span>COMPONENT INSIGHT</span><strong>{part}</strong><small>Tap a label to explore</small></div></div></section><section className="process"><div><p className="eyebrow">HOW IT WORKS</p><h2>A clear route, in three steps.</h2></div><div className="process-grid">{[[Upload,'Add your device','Upload a photo and identify its category.'],[Sparkles,'Get practical guidance','Review tailored safety and disposal advice.'],[LocateFixed,'Close the loop','Find a suitable recycler near you.']].map(([Icon,title,copy],index)=>{const Symbol=Icon as typeof Upload;return <article className="step" key={title as string}><span>0{index+1}</span><Symbol/><h3>{title as string}</h3><p>{copy as string}</p></article>})}</div></section></>}

function Analyze(){const[file,setFile]=useState<File>();const[analysis,setAnalysis]=useState<Analysis>();const[error,setError]=useState('');const[loading,setLoading]=useState(false);const submit=async()=>{if(!file)return;setLoading(true);setError('');try{setAnalysis(await api.analyze(file))}catch(e){setError(e instanceof Error?e.message:'Analysis failed.')}finally{setLoading(false)}};return <section className="page"><p className="eyebrow">DEVICE ASSESSMENT</p><h1>Make an informed next move.</h1><p className="subtle">Upload a PNG, JPEG, or WebP (up to 10 MB). Your assessment is guidance, not a certified inspection.</p><label className="dropzone"><span className="upload-icon"><Upload/></span><strong>{file?file.name:'Drop a device photo here'}</strong><small>{file?'Ready for assessment':'or click to browse files'}</small><input accept="image/png,image/jpeg,image/webp" type="file" onChange={e=>setFile(e.target.files?.[0])}/></label><button className="button primary" disabled={!file||loading} onClick={submit}>{loading?'Assessing…':'Assess device'} <ArrowRight size={18}/></button>{error&&<p className="notice error"><XCircle/> {error}</p>}{analysis&&<section className="results"><div className="metric"><span>Detected device</span><strong>{analysis.classification.object}</strong><small>{analysis.classification.category} · {Math.round(analysis.classification.confidence*100)}% confidence</small></div><div className="metric"><span>Visible condition</span><strong>{analysis.condition.condition}</strong><small>{analysis.condition.repairability}</small></div><div className="metric risk"><span>Environmental risk</span><strong>{analysis.environmental_impact.risk_level}</strong><small>{analysis.environmental_impact.environmental_impacts[0]}</small></div><article className="advice"><CheckCircle2/><div><p className="eyebrow">YOUR NEXT STEP</p><h2>{analysis.recommendation.action}</h2><p>{analysis.recommendation.reason}</p><ol>{analysis.recommendation.steps.map(step=><li key={step}>{step}</li>)}</ol></div></article>{analysis.warnings.map(warning=><p className="notice" key={warning}>{warning}</p>)}<RecyclerList recyclers={analysis.nearby_recyclers}/></section>}</section>}

function Recyclers(){const[items,setItems]=useState<Recycler[]>([]);const[message,setMessage]=useState('Use your location to see recycler options within 25 km.');const[loading,setLoading]=useState(false);const search=()=>navigator.geolocation?.getCurrentPosition(async p=>{setLoading(true);try{setItems(await api.nearby(p.coords.latitude,p.coords.longitude));setMessage('Matches are ranked by distance, compatibility, verification, pickup availability, and rating.')}catch(e){setMessage(e instanceof Error?e.message:'Search failed.')}finally{setLoading(false)}},()=>setMessage('Location access was not available. Please allow it to find nearby options.'));return <section className="page recycler-page"><p className="eyebrow">RECYCLING NETWORK</p><h1>Find the right place<br/>to close the loop.</h1><p className="subtle">Choose a location-aware option and always confirm accepted waste types before visiting.</p><button className="button primary" disabled={loading} onClick={search}><LocateFixed size={18}/>{loading?'Finding matches…':'Use my location'}</button><p className="notice">{message}</p><RecyclerList recyclers={items}/></section>}

export default function App(){const[user,setUser]=useState<User>();useEffect(()=>{if(getToken())api.me().then(setUser).catch(clearToken)},[]);const signOut=async()=>{try{await api.logout()}finally{clearToken();setUser(undefined)}};return <><Header user={user} signOut={signOut}/><main><Routes><Route path="/" element={<Home/>}/><Route path="/analyze" element={<Analyze/>}/><Route path="/recyclers" element={<Recyclers/>}/></Routes></main><footer><div><strong>EcoCycle</strong><span>Responsible technology, thoughtfully retired.</span></div><span>AI-assisted guidance · Never dispose of e-waste in general waste</span></footer></>}
